---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: seandonmooy
  labels:
    app: seandonmooy
  annotations:
    cert-manager.io/cluster-issuer: kubesail-letsencrypt
    kubernetes.io/ingress.class: caddy
spec:
  tls:
    - hosts:
        - seandonmooy.com
      secretName: seandonmooy
  rules:
    - host: seandonmooy.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: www
                port:
                  name: http-ports
