---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: seandonmooy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app: seandonmooy
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - seandonmooy.com
      secretName: seandonmooy-cert
  rules:
    - host: seandonmooy.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: www
                port:
                  number: 3003
