---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: seandonmooy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-ingress-class: nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/default-backend: www
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/http2-push-preload: "true"
  labels:
    app: seandonmooy
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - seandonmooy.com
      secretName: seandonmooy-cert
  rules:
    - host: seandonmooy.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: www
                port:
                  number: 3003
