version: 2
jobs:
  build:
    docker:
      - image: erulabs/circleci-builder:11
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Building for CI
          command: |
            yarn install --no-progress --no-emoji

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Linting & Unit testing...
          command: |
            ./bin/lint.sh

  deploy:
    docker:
      - image: erulabs/circleci-builder:11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploying to production
          command: SSH_USER=circleci NODE_ENV=production ./bin/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
